var mongoose = require('mongoose');
mongoose.Promise = require('bluebird');
// set Promise provider to bluebird
var schema = new mongoose.Schema(
  {'an':String,
  'spec':String,
  'grupa':String,
  'sgr':String,
  'l1':String,
  'l2':String,
  'l3':String,
  'l4':String,
  'l5':String,
  'l6':String,
  'l7':String,
  'm1':String,
  'm2':String,
  'm3':String,
  'm4':String,
  'm5':String,
  'm6':String,
  'm7':String,
  'mi1':String,
  'mi2':String,
  'mi3':String,
  'mi4':String,
  'mi5':String,
  'mi6':String,
  'mi7':String,
  'j1':String,
  'j2':String,
  'j3':String,
  'j4':String,
  'j5':String,
  'j6':String,
  'j7':String,
  'v1':String,
  'v2':String,
  'v3':String,
  'v4':String,
  'v5':String,
  'v6':String,
  'v7':String,
  saptamana_para:Boolean
});
module.exports = mongoose.model('Orar', schema);
